#makefile
SOURCES8 = main.cpp StringStackQueue.cpp
SOURCES10 = main.cpp StackQueue.h

wk8: $(SOURCES8)
	@g++ -std=c++11 -g -Wall -o main $(SOURCES8)
	@./main

wk10: $(SOURCES10)
	@g++ -std=c++11 -g -Wall -o main $(SOURCES10)
	@./main
